plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.devtools.ksp'
    id 'com.google.dagger.hilt.android'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.dagger.hilt.android'

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.jeanloth.project.android.kotlin.feedme"
        minSdk 32 // Android 12
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        debug {
            buildConfigField("int", "DATABASE_VERSION", '1')
            debuggable true
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            buildConfigField("int", "DATABASE_VERSION", '1')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += [
          "-Xopt-in=kotlin.RequiresOptIn"
        ]
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_compiler

        // Hilt uses Java 8 features
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    namespace 'com.jeanloth.project.android.kotlin.feedme'
}

// Allow references to generated code
kapt {
    correctErrorTypes = true
}

dependencies {
    /* ---- Variables ---- */

    def room_version = "2.6.1"
    def nav_version = "2.8.1"

    /* ---- Compose BOM & compiler ---- */

    def composeBom = platform("androidx.compose:compose-bom:2024.09.02")
    implementation(composeBom)
    testImplementation(composeBom)
    androidTestImplementation(composeBom)
    // Compose compiler is not included in BOM : https://developer.android.com/develop/ui/compose/bom#why_isnt_the_compose_compiler_library_included_in_the_bom
    // But must be compatible ith Kotlin version : https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility
    implementation "androidx.compose.compiler:compiler:$compose_compiler"
    implementation "androidx.constraintlayout:constraintlayout-compose:1.0.1"

    /* ---- Compose BOM Libraries ---- */
    // BOM Library versions : https://developer.android.com/develop/ui/compose/bom/bom-mapping

    implementation "androidx.compose.ui:ui"
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation "androidx.activity:activity-compose"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose"
    implementation "androidx.compose.runtime:runtime"
    implementation 'androidx.compose.foundation:foundation-android'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    /* ---- Others ---- */

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.5'
    implementation "androidx.navigation:navigation-compose:$nav_version"

    /* ---- Room ---- */

    implementation "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    // optional - Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"

    //Dagger - Hilt
    implementation "com.google.dagger:hilt-android:2.51.1"
    kapt "com.google.dagger:hilt-compiler:2.51.1"
    implementation "androidx.hilt:hilt-navigation-compose:1.2.0"
   /* implementation 'com.google.dagger:hilt-android:2.49'
    kapt 'com.google.dagger:hilt-compiler:2.43'
    kapt 'androidx.hilt:hilt-compiler:1.2.0'
    implementation "androidx.hilt:hilt-navigation-compose:1.2.0"*/

    // Accompanist for keyboard and form fields
    implementation "com.google.accompanist:accompanist-insets:0.24.1-alpha"
    // Glide
    implementation 'com.google.accompanist:accompanist-glide:0.9.1'

    // Material icon extended
    implementation "androidx.compose.material:material-icons-extended:1.7.2"

    // Splitties
    implementation "com.louiscad.splitties:splitties-fun-pack-android-base:3.0.0"

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.7.2'
    implementation 'com.squareup.retrofit2:converter-gson:2.7.2'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation "com.squareup.okhttp3:logging-interceptor:4.9.0"

    // Open Street Map
    implementation 'org.osmdroid:osmdroid-android:6.1.2'
    //implementation 'com.github.MKergall:osmbonuspack:6.4'

    // Google maps for compose
    implementation 'com.google.maps.android:maps-compose:2.7.3'
    // Make sure to also include the latest version of the Maps SDK for Android
    implementation 'com.google.android.gms:play-services-maps:19.0.0'

    // Coil
    implementation("io.coil-kt:coil-compose:1.3.2")

    // Moshi
    implementation "com.squareup.moshi:moshi-kotlin:1.14.0"

    // Tests
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    // Truth
    testImplementation "com.google.truth:truth:1.1.3"
}