@startuml

skinparam object {
    BackgroundColor Snow
    BorderColor Purple
    ArrowColor Purple
}

object Client{
    <u>idClient</u> : Long auto_increment
    ..
    firstname : String not null
    phoneNumber : Int?
}

object PaymentType{
    CARD,
    CASH,
    PAYPAL,
    OTHER
}

object Payment {
    idPayment : Long auto_increment
    ..
    paymentAmount : Double
    paymentType : PaymentType
}

object Command{
    <u>id</u> : Int auto_increment
    ..
    deliveryDate : LocalDateTime?
    status : StatusType
    totalPrice : Double
    productWrappers : List<ProductWrapper>
    basketWrappers : List<BasketWrapper>

    clientId : Long
    paymentId : Long
}

object Product {
    <u>id</u> : Int auto_increment
    ..
    product : Product
    count : Int
}

object Basket {
    <u>id</u> : Int auto_increment
    ..
    label : String
    price : Int
    wrappers : List<Wrapper<Product>>
    --
    price : Double
}

object Wrapper {
    <u>id</u> : Int auto_increment
        ..
    item : T,
    basketId : Long = 0L,
    quantity : Int = 0,
    status : Status
    --
    totalPrice : Double
}

object ProductWrapperStatus{
    TO_DO,
    IN_PROGRESS,
    DONE,
    CANCELED,
}

object StatusType{
    TO_DO,
    IN_PROGRESS,
    DONE,
    DELIVERED,
    CANCELED,
    PAYED
}

object Product{
    <u>id</u> : Int auto_increment
    ..
    label : String
    img : String
}

object ProductCategory {
    FRUITS,
    VEGETABLE,
    OTHER
}

Payment "1" --right-- "1" PaymentType : a
Command "1" --right-- "1" Payment : a
Command "1" --left-- "1" Client : a
Command "1" -down- "1" ProductWrapper : possède
Command "1" -down- "1" BasketWrapper : possède
Command "1" -- "1" StatusType : a
Basket "1" -- "1" StatusType : a
Product "1" --right-- "1" StatusType : a
Product "1..n" --left-- "1" ProductCategory : est


@enduml

